name: ume_core
description: UME is an in-app debug kits platform for Flutter apps.
version: 2.0.1
homepage: https://github.com/ume-community/ume

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.15

  # [Original]: vm_service: ">=9.4.0 <12.0.0"
  vm_service: ^14.2.5

  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  melos: ^6.2.0
  mockito: ^5.3.2
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65
  # lints: ^5.1.0

flutter:
  uses-material-design: true
